### ISSUE TITLE
Remove dots in comments

### ISSUE THREAD

**Issue by adrienlucbert** [DarkOceanInteractive/project-conventions#2]
Remove dots in comments.

![image](https://user-images.githubusercontent.com/42178413/163171298-83629468-3ed3-4076-be86-5bd3d3ec45e8.png)

**Comment by andysmit1** [comment]
I agree, This is a mayor issue which we all overlooked and should be fixed immediately 
(As a matter of fact, i'm not going to be using any dots in this comment)

**Comment by NAkbulut** [comment]
I am an imperfect being, but this does not justify the mistakes that I have made to you. I understand that even if I say sorry, it will not change anything. However, I will keep my promise that I will change because I want to become a better person for you.
